Delete from UsuariosInyeccion;
Insert UsuariosInyeccion values ('Usuario 01','123', 1);
Insert UsuariosInyeccion values ('Usuario 02','123', 1);
Insert UsuariosInyeccion values ('Usuario 03','123', 1);
Insert UsuariosInyeccion values ('Usuario 04','123', 1);
Insert UsuariosInyeccion values ('Usuario 05','123', 1);
Insert UsuariosInyeccion values ('Usuario 06','123', 0);
Insert UsuariosInyeccion values ('Usuario 07','123', 0);
Insert UsuariosInyeccion values ('Usuario 08','123', 0);
Insert UsuariosInyeccion values ('Usuario 09','123', 0);
Insert UsuariosInyeccion values ('Usuario 10','123', 0);