

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoWeb.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProyectoBDEntities : DbContext
{
    public ProyectoBDEntities()
        : base("name=ProyectoBDEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<UsuariosInyeccion> UsuariosInyeccions { get; set; }

}

}

